package testcasesupport;

import javax.servlet.http.*;

public class ServletMain extends HttpServlet {

	private static final long serialVersionUID = 1L; /* needed since Servlets are serializable */
	
	

	public void doPost(HttpServletRequest request, HttpServletResponse response) {
		doGet(request, response);
	}

	public void doGet(HttpServletRequest request, HttpServletResponse response) {
		doGetCWE1(request, response);
		doGetCWE2(request, response);
		doGetCWE3(request, response);
		doGetCWE4(request, response);
		doGetCWE5(request, response);
		doGetCWE6(request, response);
		doGetCWE7(request, response);
		doGetCWE8(request, response);
		doGetCWE9(request, response);
	}
	
	private static void doGetCWE1(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-1 */
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_01()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_02()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_03()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_04()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_05()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_06()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_07()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_08()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_09()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_10()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_11()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_12()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_13()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_14()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_15()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_16()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_17()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_19()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_31()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_41()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_42()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_45()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_51a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_52a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_53a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_54a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_61a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_66a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_67a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_add_68a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_01()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_02()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_03()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_04()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_05()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_06()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_07()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_08()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_09()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_10()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_11()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_12()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_13()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_14()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_15()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_16()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_17()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_19()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_31()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_41()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_42()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_45()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_51a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_52a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_53a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_54a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_61a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_66a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_67a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_multiply_68a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_01()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_02()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_03()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_04()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_05()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_06()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_07()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_08()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_09()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_10()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_11()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_12()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_13()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_14()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_15()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_16()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_17()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_19()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_31()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_41()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_42()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_45()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_51a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_52a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_53a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_54a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_61a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_66a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_67a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getCookiesServlet_square_68a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_01()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_02()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_03()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_04()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_05()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_06()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_07()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_08()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_09()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_10()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_11()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_12()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_13()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_14()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_15()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_16()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_17()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_19()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_31()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_41()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_42()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_45()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_51a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_52a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_53a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_54a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_61a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_66a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_67a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_add_68a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_01()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_02()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_03()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_04()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_05()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_06()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_07()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_08()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_09()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_10()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_11()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_12()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_13()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_14()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_15()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_16()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_17()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_19()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_31()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_41()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_42()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_45()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_51a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_52a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_53a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_54a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_61a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_66a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_67a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_multiply_68a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_01()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_02()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_03()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_04()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_05()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_06()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_07()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_08()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_09()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_10()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_11()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_12()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_13()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_14()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_15()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_16()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_17()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_19()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_31()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_41()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_42()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_45()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_51a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_52a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_53a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_54a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_61a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_66a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_67a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getParameterServlet_square_68a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_01()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_02()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_03()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_04()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_05()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_06()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_07()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_08()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_09()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_10()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_11()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_12()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_13()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_14()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_15()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_16()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_17()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_19()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_31()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_41()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_42()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_45()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_51a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_52a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_53a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_54a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_61a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_66a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_67a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_add_68a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_01()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_02()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_03()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_04()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_05()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_06()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_07()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_08()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_09()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_10()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_11()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_12()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_13()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_14()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_15()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_16()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_17()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_19()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_31()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_41()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_42()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_45()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_51a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_52a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_53a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_54a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_61a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_66a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_67a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_multiply_68a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_01()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_02()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_03()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_04()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_05()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_06()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_07()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_08()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_09()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_10()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_11()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_12()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_13()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_14()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_15()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_16()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_17()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_19()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_31()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_41()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_42()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_45()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_51a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_52a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_53a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_54a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_61a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_66a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_67a()).runTest(request, response);
			(new testcases.CWE190_Integer_Overflow.CWE190_Integer_Overflow__getQueryStringServlet_square_68a()).runTest(request, response);
			/* END-AUTOGENERATED-SERVLET-TESTS-1 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE1 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}
		
	private static void doGetCWE2(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-2 */

			/* END-AUTOGENERATED-SERVLET-TESTS-2 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE2 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}
		
	private static void doGetCWE3(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-3 */

			/* END-AUTOGENERATED-SERVLET-TESTS-3 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE3 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}

	private static void doGetCWE4(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-4 */

			/* END-AUTOGENERATED-SERVLET-TESTS-4 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE4 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}
		
	private static void doGetCWE5(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-5 */

			/* END-AUTOGENERATED-SERVLET-TESTS-5 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE5 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {

				System.out.println("  " + ste.toString());
			} 
		}
	}		
		
	private static void doGetCWE6(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-6 */

			/* END-AUTOGENERATED-SERVLET-TESTS-6 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE6 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}

	private static void doGetCWE7(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-7 */

			/* END-AUTOGENERATED-SERVLET-TESTS-7 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE7 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}		
	
	private static void doGetCWE8(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-8 */

			/* END-AUTOGENERATED-SERVLET-TESTS-8 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE8 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}	
	
	private static void doGetCWE9(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-9 */

			/* END-AUTOGENERATED-SERVLET-TESTS-9 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE9 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}		
}
