package testcasesupport;

public class Main {

	public static void main(String[] args) {
		
		if(args.length != 0) {
		
			if(args[0].equals("-h") || args[0].equals("--help")) {
		
				System.err.println("To use this main, you can either run the program with no " +
				"command line arguments to run all test cases or you can specify one or more classes to test");
				System.err.println("For example:");
				System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
				System.exit(1);
			}
			
			/* User supplied some class names on the command line, just use those with introspection
			 *
			 * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
			 *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
 			 * could read class names from command line or use
			 * http://sadun-util.sourceforge.net/api/org/sadun/util/
			 * ClassPackageExplorer.html
			 */

			for (String className : args) {

				try {
					
					/* String classNameWithPackage = "testcases." + className; */
					
					/* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

					Class<?> myClass = Class.forName(className);

					AbstractTestCase myObject = (AbstractTestCase) myClass
							.newInstance();

					myObject.runTest(className);

				} catch (Exception ex) {

					IO.writeLine("Could not run test for class " + className);
					ex.printStackTrace();

				}
				
				IO.writeLine(""); /* leave a blank line between classes */

			}

		} else {
		
			/* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
			runTestCWE1();
			runTestCWE2();
			runTestCWE3();
			runTestCWE4();
			runTestCWE5();
			runTestCWE6();
			runTestCWE7();
			runTestCWE8();
			runTestCWE9();
		}			
	}

private static void runTestCWE1() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */

			/* END-AUTOGENERATED-JAVA-TESTS-1 */
}

private static void runTestCWE2() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

			/* END-AUTOGENERATED-JAVA-TESTS-2 */
}

private static void runTestCWE3() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

			/* END-AUTOGENERATED-JAVA-TESTS-3 */
}

private static void runTestCWE4() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_01()).runTest("CWE470_Unsafe_Reflection__connect_tcp_01");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_02()).runTest("CWE470_Unsafe_Reflection__connect_tcp_02");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_03()).runTest("CWE470_Unsafe_Reflection__connect_tcp_03");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_04()).runTest("CWE470_Unsafe_Reflection__connect_tcp_04");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_05()).runTest("CWE470_Unsafe_Reflection__connect_tcp_05");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_06()).runTest("CWE470_Unsafe_Reflection__connect_tcp_06");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_07()).runTest("CWE470_Unsafe_Reflection__connect_tcp_07");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_08()).runTest("CWE470_Unsafe_Reflection__connect_tcp_08");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_09()).runTest("CWE470_Unsafe_Reflection__connect_tcp_09");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_10()).runTest("CWE470_Unsafe_Reflection__connect_tcp_10");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_11()).runTest("CWE470_Unsafe_Reflection__connect_tcp_11");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_12()).runTest("CWE470_Unsafe_Reflection__connect_tcp_12");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_13()).runTest("CWE470_Unsafe_Reflection__connect_tcp_13");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_14()).runTest("CWE470_Unsafe_Reflection__connect_tcp_14");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_15()).runTest("CWE470_Unsafe_Reflection__connect_tcp_15");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_16()).runTest("CWE470_Unsafe_Reflection__connect_tcp_16");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_17()).runTest("CWE470_Unsafe_Reflection__connect_tcp_17");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_19()).runTest("CWE470_Unsafe_Reflection__connect_tcp_19");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_31()).runTest("CWE470_Unsafe_Reflection__connect_tcp_31");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_41()).runTest("CWE470_Unsafe_Reflection__connect_tcp_41");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_42()).runTest("CWE470_Unsafe_Reflection__connect_tcp_42");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_45()).runTest("CWE470_Unsafe_Reflection__connect_tcp_45");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_51a()).runTest("CWE470_Unsafe_Reflection__connect_tcp_51a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_52a()).runTest("CWE470_Unsafe_Reflection__connect_tcp_52a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_53a()).runTest("CWE470_Unsafe_Reflection__connect_tcp_53a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_54a()).runTest("CWE470_Unsafe_Reflection__connect_tcp_54a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_61a()).runTest("CWE470_Unsafe_Reflection__connect_tcp_61a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_66a()).runTest("CWE470_Unsafe_Reflection__connect_tcp_66a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_67a()).runTest("CWE470_Unsafe_Reflection__connect_tcp_67a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_68a()).runTest("CWE470_Unsafe_Reflection__connect_tcp_68a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__connect_tcp_71a()).runTest("CWE470_Unsafe_Reflection__connect_tcp_71a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_01()).runTest("CWE470_Unsafe_Reflection__console_readLine_01");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_02()).runTest("CWE470_Unsafe_Reflection__console_readLine_02");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_03()).runTest("CWE470_Unsafe_Reflection__console_readLine_03");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_04()).runTest("CWE470_Unsafe_Reflection__console_readLine_04");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_05()).runTest("CWE470_Unsafe_Reflection__console_readLine_05");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_06()).runTest("CWE470_Unsafe_Reflection__console_readLine_06");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_07()).runTest("CWE470_Unsafe_Reflection__console_readLine_07");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_08()).runTest("CWE470_Unsafe_Reflection__console_readLine_08");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_09()).runTest("CWE470_Unsafe_Reflection__console_readLine_09");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_10()).runTest("CWE470_Unsafe_Reflection__console_readLine_10");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_11()).runTest("CWE470_Unsafe_Reflection__console_readLine_11");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_12()).runTest("CWE470_Unsafe_Reflection__console_readLine_12");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_13()).runTest("CWE470_Unsafe_Reflection__console_readLine_13");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_14()).runTest("CWE470_Unsafe_Reflection__console_readLine_14");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_15()).runTest("CWE470_Unsafe_Reflection__console_readLine_15");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_16()).runTest("CWE470_Unsafe_Reflection__console_readLine_16");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_17()).runTest("CWE470_Unsafe_Reflection__console_readLine_17");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_19()).runTest("CWE470_Unsafe_Reflection__console_readLine_19");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_31()).runTest("CWE470_Unsafe_Reflection__console_readLine_31");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_41()).runTest("CWE470_Unsafe_Reflection__console_readLine_41");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_42()).runTest("CWE470_Unsafe_Reflection__console_readLine_42");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_45()).runTest("CWE470_Unsafe_Reflection__console_readLine_45");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_51a()).runTest("CWE470_Unsafe_Reflection__console_readLine_51a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_52a()).runTest("CWE470_Unsafe_Reflection__console_readLine_52a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_53a()).runTest("CWE470_Unsafe_Reflection__console_readLine_53a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_54a()).runTest("CWE470_Unsafe_Reflection__console_readLine_54a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_61a()).runTest("CWE470_Unsafe_Reflection__console_readLine_61a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_66a()).runTest("CWE470_Unsafe_Reflection__console_readLine_66a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_67a()).runTest("CWE470_Unsafe_Reflection__console_readLine_67a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_68a()).runTest("CWE470_Unsafe_Reflection__console_readLine_68a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__console_readLine_71a()).runTest("CWE470_Unsafe_Reflection__console_readLine_71a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_01()).runTest("CWE470_Unsafe_Reflection__Environment_01");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_02()).runTest("CWE470_Unsafe_Reflection__Environment_02");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_03()).runTest("CWE470_Unsafe_Reflection__Environment_03");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_04()).runTest("CWE470_Unsafe_Reflection__Environment_04");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_05()).runTest("CWE470_Unsafe_Reflection__Environment_05");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_06()).runTest("CWE470_Unsafe_Reflection__Environment_06");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_07()).runTest("CWE470_Unsafe_Reflection__Environment_07");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_08()).runTest("CWE470_Unsafe_Reflection__Environment_08");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_09()).runTest("CWE470_Unsafe_Reflection__Environment_09");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_10()).runTest("CWE470_Unsafe_Reflection__Environment_10");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_11()).runTest("CWE470_Unsafe_Reflection__Environment_11");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_12()).runTest("CWE470_Unsafe_Reflection__Environment_12");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_13()).runTest("CWE470_Unsafe_Reflection__Environment_13");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_14()).runTest("CWE470_Unsafe_Reflection__Environment_14");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_15()).runTest("CWE470_Unsafe_Reflection__Environment_15");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_16()).runTest("CWE470_Unsafe_Reflection__Environment_16");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_17()).runTest("CWE470_Unsafe_Reflection__Environment_17");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_19()).runTest("CWE470_Unsafe_Reflection__Environment_19");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_31()).runTest("CWE470_Unsafe_Reflection__Environment_31");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_41()).runTest("CWE470_Unsafe_Reflection__Environment_41");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_42()).runTest("CWE470_Unsafe_Reflection__Environment_42");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_45()).runTest("CWE470_Unsafe_Reflection__Environment_45");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_51a()).runTest("CWE470_Unsafe_Reflection__Environment_51a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_52a()).runTest("CWE470_Unsafe_Reflection__Environment_52a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_53a()).runTest("CWE470_Unsafe_Reflection__Environment_53a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_54a()).runTest("CWE470_Unsafe_Reflection__Environment_54a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_61a()).runTest("CWE470_Unsafe_Reflection__Environment_61a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_66a()).runTest("CWE470_Unsafe_Reflection__Environment_66a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_67a()).runTest("CWE470_Unsafe_Reflection__Environment_67a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_68a()).runTest("CWE470_Unsafe_Reflection__Environment_68a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__Environment_71a()).runTest("CWE470_Unsafe_Reflection__Environment_71a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_01()).runTest("CWE470_Unsafe_Reflection__fromDB_01");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_02()).runTest("CWE470_Unsafe_Reflection__fromDB_02");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_03()).runTest("CWE470_Unsafe_Reflection__fromDB_03");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_04()).runTest("CWE470_Unsafe_Reflection__fromDB_04");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_05()).runTest("CWE470_Unsafe_Reflection__fromDB_05");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_06()).runTest("CWE470_Unsafe_Reflection__fromDB_06");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_07()).runTest("CWE470_Unsafe_Reflection__fromDB_07");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_08()).runTest("CWE470_Unsafe_Reflection__fromDB_08");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_09()).runTest("CWE470_Unsafe_Reflection__fromDB_09");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_10()).runTest("CWE470_Unsafe_Reflection__fromDB_10");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_11()).runTest("CWE470_Unsafe_Reflection__fromDB_11");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_12()).runTest("CWE470_Unsafe_Reflection__fromDB_12");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_13()).runTest("CWE470_Unsafe_Reflection__fromDB_13");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_14()).runTest("CWE470_Unsafe_Reflection__fromDB_14");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_15()).runTest("CWE470_Unsafe_Reflection__fromDB_15");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_16()).runTest("CWE470_Unsafe_Reflection__fromDB_16");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_17()).runTest("CWE470_Unsafe_Reflection__fromDB_17");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_19()).runTest("CWE470_Unsafe_Reflection__fromDB_19");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_31()).runTest("CWE470_Unsafe_Reflection__fromDB_31");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_41()).runTest("CWE470_Unsafe_Reflection__fromDB_41");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_42()).runTest("CWE470_Unsafe_Reflection__fromDB_42");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_45()).runTest("CWE470_Unsafe_Reflection__fromDB_45");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_51a()).runTest("CWE470_Unsafe_Reflection__fromDB_51a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_52a()).runTest("CWE470_Unsafe_Reflection__fromDB_52a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_53a()).runTest("CWE470_Unsafe_Reflection__fromDB_53a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_54a()).runTest("CWE470_Unsafe_Reflection__fromDB_54a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_61a()).runTest("CWE470_Unsafe_Reflection__fromDB_61a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_66a()).runTest("CWE470_Unsafe_Reflection__fromDB_66a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_67a()).runTest("CWE470_Unsafe_Reflection__fromDB_67a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_68a()).runTest("CWE470_Unsafe_Reflection__fromDB_68a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromDB_71a()).runTest("CWE470_Unsafe_Reflection__fromDB_71a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_01()).runTest("CWE470_Unsafe_Reflection__fromFile_01");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_02()).runTest("CWE470_Unsafe_Reflection__fromFile_02");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_03()).runTest("CWE470_Unsafe_Reflection__fromFile_03");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_04()).runTest("CWE470_Unsafe_Reflection__fromFile_04");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_05()).runTest("CWE470_Unsafe_Reflection__fromFile_05");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_06()).runTest("CWE470_Unsafe_Reflection__fromFile_06");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_07()).runTest("CWE470_Unsafe_Reflection__fromFile_07");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_08()).runTest("CWE470_Unsafe_Reflection__fromFile_08");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_09()).runTest("CWE470_Unsafe_Reflection__fromFile_09");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_10()).runTest("CWE470_Unsafe_Reflection__fromFile_10");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_11()).runTest("CWE470_Unsafe_Reflection__fromFile_11");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_12()).runTest("CWE470_Unsafe_Reflection__fromFile_12");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_13()).runTest("CWE470_Unsafe_Reflection__fromFile_13");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_14()).runTest("CWE470_Unsafe_Reflection__fromFile_14");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_15()).runTest("CWE470_Unsafe_Reflection__fromFile_15");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_16()).runTest("CWE470_Unsafe_Reflection__fromFile_16");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_17()).runTest("CWE470_Unsafe_Reflection__fromFile_17");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_19()).runTest("CWE470_Unsafe_Reflection__fromFile_19");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_31()).runTest("CWE470_Unsafe_Reflection__fromFile_31");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_41()).runTest("CWE470_Unsafe_Reflection__fromFile_41");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_42()).runTest("CWE470_Unsafe_Reflection__fromFile_42");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_45()).runTest("CWE470_Unsafe_Reflection__fromFile_45");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_51a()).runTest("CWE470_Unsafe_Reflection__fromFile_51a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_52a()).runTest("CWE470_Unsafe_Reflection__fromFile_52a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_53a()).runTest("CWE470_Unsafe_Reflection__fromFile_53a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_54a()).runTest("CWE470_Unsafe_Reflection__fromFile_54a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_61a()).runTest("CWE470_Unsafe_Reflection__fromFile_61a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_66a()).runTest("CWE470_Unsafe_Reflection__fromFile_66a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_67a()).runTest("CWE470_Unsafe_Reflection__fromFile_67a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_68a()).runTest("CWE470_Unsafe_Reflection__fromFile_68a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__fromFile_71a()).runTest("CWE470_Unsafe_Reflection__fromFile_71a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_01()).runTest("CWE470_Unsafe_Reflection__listen_tcp_01");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_02()).runTest("CWE470_Unsafe_Reflection__listen_tcp_02");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_03()).runTest("CWE470_Unsafe_Reflection__listen_tcp_03");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_04()).runTest("CWE470_Unsafe_Reflection__listen_tcp_04");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_05()).runTest("CWE470_Unsafe_Reflection__listen_tcp_05");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_06()).runTest("CWE470_Unsafe_Reflection__listen_tcp_06");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_07()).runTest("CWE470_Unsafe_Reflection__listen_tcp_07");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_08()).runTest("CWE470_Unsafe_Reflection__listen_tcp_08");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_09()).runTest("CWE470_Unsafe_Reflection__listen_tcp_09");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_10()).runTest("CWE470_Unsafe_Reflection__listen_tcp_10");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_11()).runTest("CWE470_Unsafe_Reflection__listen_tcp_11");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_12()).runTest("CWE470_Unsafe_Reflection__listen_tcp_12");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_13()).runTest("CWE470_Unsafe_Reflection__listen_tcp_13");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_14()).runTest("CWE470_Unsafe_Reflection__listen_tcp_14");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_15()).runTest("CWE470_Unsafe_Reflection__listen_tcp_15");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_16()).runTest("CWE470_Unsafe_Reflection__listen_tcp_16");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_17()).runTest("CWE470_Unsafe_Reflection__listen_tcp_17");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_19()).runTest("CWE470_Unsafe_Reflection__listen_tcp_19");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_31()).runTest("CWE470_Unsafe_Reflection__listen_tcp_31");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_41()).runTest("CWE470_Unsafe_Reflection__listen_tcp_41");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_42()).runTest("CWE470_Unsafe_Reflection__listen_tcp_42");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_45()).runTest("CWE470_Unsafe_Reflection__listen_tcp_45");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_51a()).runTest("CWE470_Unsafe_Reflection__listen_tcp_51a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_52a()).runTest("CWE470_Unsafe_Reflection__listen_tcp_52a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_53a()).runTest("CWE470_Unsafe_Reflection__listen_tcp_53a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_54a()).runTest("CWE470_Unsafe_Reflection__listen_tcp_54a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_61a()).runTest("CWE470_Unsafe_Reflection__listen_tcp_61a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_66a()).runTest("CWE470_Unsafe_Reflection__listen_tcp_66a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_67a()).runTest("CWE470_Unsafe_Reflection__listen_tcp_67a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_68a()).runTest("CWE470_Unsafe_Reflection__listen_tcp_68a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__listen_tcp_71a()).runTest("CWE470_Unsafe_Reflection__listen_tcp_71a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_01()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_01");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_02()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_02");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_03()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_03");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_04()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_04");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_05()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_05");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_06()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_06");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_07()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_07");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_08()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_08");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_09()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_09");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_10()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_10");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_11()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_11");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_12()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_12");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_13()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_13");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_14()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_14");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_15()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_15");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_16()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_16");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_17()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_17");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_19()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_19");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_31()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_31");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_41()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_41");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_42()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_42");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_45()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_45");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_51a()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_51a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_52a()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_52a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_53a()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_53a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_54a()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_54a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_61a()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_61a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_66a()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_66a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_67a()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_67a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_68a()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_68a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__PropertiesFile_71a()).runTest("CWE470_Unsafe_Reflection__PropertiesFile_71a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_01()).runTest("CWE470_Unsafe_Reflection__URLConnection_01");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_02()).runTest("CWE470_Unsafe_Reflection__URLConnection_02");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_03()).runTest("CWE470_Unsafe_Reflection__URLConnection_03");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_04()).runTest("CWE470_Unsafe_Reflection__URLConnection_04");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_05()).runTest("CWE470_Unsafe_Reflection__URLConnection_05");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_06()).runTest("CWE470_Unsafe_Reflection__URLConnection_06");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_07()).runTest("CWE470_Unsafe_Reflection__URLConnection_07");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_08()).runTest("CWE470_Unsafe_Reflection__URLConnection_08");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_09()).runTest("CWE470_Unsafe_Reflection__URLConnection_09");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_10()).runTest("CWE470_Unsafe_Reflection__URLConnection_10");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_11()).runTest("CWE470_Unsafe_Reflection__URLConnection_11");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_12()).runTest("CWE470_Unsafe_Reflection__URLConnection_12");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_13()).runTest("CWE470_Unsafe_Reflection__URLConnection_13");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_14()).runTest("CWE470_Unsafe_Reflection__URLConnection_14");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_15()).runTest("CWE470_Unsafe_Reflection__URLConnection_15");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_16()).runTest("CWE470_Unsafe_Reflection__URLConnection_16");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_17()).runTest("CWE470_Unsafe_Reflection__URLConnection_17");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_19()).runTest("CWE470_Unsafe_Reflection__URLConnection_19");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_31()).runTest("CWE470_Unsafe_Reflection__URLConnection_31");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_41()).runTest("CWE470_Unsafe_Reflection__URLConnection_41");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_42()).runTest("CWE470_Unsafe_Reflection__URLConnection_42");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_45()).runTest("CWE470_Unsafe_Reflection__URLConnection_45");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_51a()).runTest("CWE470_Unsafe_Reflection__URLConnection_51a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_52a()).runTest("CWE470_Unsafe_Reflection__URLConnection_52a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_53a()).runTest("CWE470_Unsafe_Reflection__URLConnection_53a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_54a()).runTest("CWE470_Unsafe_Reflection__URLConnection_54a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_61a()).runTest("CWE470_Unsafe_Reflection__URLConnection_61a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_66a()).runTest("CWE470_Unsafe_Reflection__URLConnection_66a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_67a()).runTest("CWE470_Unsafe_Reflection__URLConnection_67a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_68a()).runTest("CWE470_Unsafe_Reflection__URLConnection_68a");
			(new testcases.CWE470_Unsafe_Reflection.CWE470_Unsafe_Reflection__URLConnection_71a()).runTest("CWE470_Unsafe_Reflection__URLConnection_71a");
			/* END-AUTOGENERATED-JAVA-TESTS-4 */
}

private static void runTestCWE5() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

			/* END-AUTOGENERATED-JAVA-TESTS-5 */
}

private static void runTestCWE6() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

			/* END-AUTOGENERATED-JAVA-TESTS-6 */
}

private static void runTestCWE7() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

			/* END-AUTOGENERATED-JAVA-TESTS-7 */
}

private static void runTestCWE8() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

			/* END-AUTOGENERATED-JAVA-TESTS-8 */
}

private static void runTestCWE9() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

			/* END-AUTOGENERATED-JAVA-TESTS-9 */
}
}