package testcasesupport;

public class Main {

	public static void main(String[] args) {
		
		if(args.length != 0) {
		
			if(args[0].equals("-h") || args[0].equals("--help")) {
		
				System.err.println("To use this main, you can either run the program with no " +
				"command line arguments to run all test cases or you can specify one or more classes to test");
				System.err.println("For example:");
				System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
				System.exit(1);
			}
			
			/* User supplied some class names on the command line, just use those with introspection
			 *
			 * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
			 *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
 			 * could read class names from command line or use
			 * http://sadun-util.sourceforge.net/api/org/sadun/util/
			 * ClassPackageExplorer.html
			 */

			for (String className : args) {

				try {
					
					/* String classNameWithPackage = "testcases." + className; */
					
					/* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

					Class<?> myClass = Class.forName(className);

					AbstractTestCase myObject = (AbstractTestCase) myClass
							.newInstance();

					myObject.runTest(className);

				} catch (Exception ex) {

					IO.writeLine("Could not run test for class " + className);
					ex.printStackTrace();

				}
				
				IO.writeLine(""); /* leave a blank line between classes */

			}

		} else {
		
			/* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
			runTestCWE1();
			runTestCWE2();
			runTestCWE3();
			runTestCWE4();
			runTestCWE5();
			runTestCWE6();
			runTestCWE7();
			runTestCWE8();
			runTestCWE9();
		}			
	}

private static void runTestCWE1() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_01()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_01");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_02()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_02");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_03()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_03");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_04()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_04");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_05()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_05");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_06()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_06");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_07()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_07");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_08()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_08");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_09()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_09");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_10()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_10");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_11()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_11");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_12()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_12");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_13()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_13");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_14()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_14");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_15()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_15");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_16()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_16");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_17()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_17");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_19()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_19");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_31()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_31");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_41()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_41");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_42()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_42");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_45()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_45");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_51a()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_51a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_52a()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_52a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_53a()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_53a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_54a()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_54a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_61a()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_61a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_66a()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_66a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_67a()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_67a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_multiply_68a()).runTest("CWE191_Integer_Underflow__connect_tcp_multiply_68a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_01()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_01");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_02()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_02");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_03()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_03");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_04()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_04");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_05()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_05");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_06()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_06");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_07()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_07");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_08()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_08");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_09()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_09");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_10()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_10");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_11()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_11");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_12()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_12");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_13()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_13");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_14()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_14");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_15()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_15");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_16()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_16");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_17()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_17");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_19()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_19");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_31()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_31");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_41()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_41");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_42()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_42");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_45()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_45");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_51a()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_51a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_52a()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_52a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_53a()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_53a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_54a()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_54a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_61a()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_61a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_66a()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_66a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_67a()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_67a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__connect_tcp_subtract_68a()).runTest("CWE191_Integer_Underflow__connect_tcp_subtract_68a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_01()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_01");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_02()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_02");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_03()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_03");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_04()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_04");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_05()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_05");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_06()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_06");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_07()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_07");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_08()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_08");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_09()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_09");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_10()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_10");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_11()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_11");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_12()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_12");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_13()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_13");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_14()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_14");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_15()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_15");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_16()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_16");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_17()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_17");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_19()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_19");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_31()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_31");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_41()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_41");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_42()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_42");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_45()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_45");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_51a()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_51a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_52a()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_52a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_53a()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_53a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_54a()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_54a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_61a()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_61a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_66a()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_66a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_67a()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_67a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_multiply_68a()).runTest("CWE191_Integer_Underflow__console_readLine_multiply_68a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_01()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_01");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_02()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_02");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_03()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_03");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_04()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_04");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_05()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_05");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_06()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_06");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_07()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_07");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_08()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_08");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_09()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_09");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_10()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_10");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_11()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_11");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_12()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_12");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_13()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_13");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_14()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_14");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_15()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_15");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_16()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_16");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_17()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_17");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_19()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_19");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_31()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_31");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_41()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_41");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_42()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_42");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_45()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_45");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_51a()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_51a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_52a()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_52a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_53a()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_53a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_54a()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_54a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_61a()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_61a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_66a()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_66a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_67a()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_67a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__console_readLine_subtract_68a()).runTest("CWE191_Integer_Underflow__console_readLine_subtract_68a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_01()).runTest("CWE191_Integer_Underflow__Environment_multiply_01");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_02()).runTest("CWE191_Integer_Underflow__Environment_multiply_02");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_03()).runTest("CWE191_Integer_Underflow__Environment_multiply_03");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_04()).runTest("CWE191_Integer_Underflow__Environment_multiply_04");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_05()).runTest("CWE191_Integer_Underflow__Environment_multiply_05");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_06()).runTest("CWE191_Integer_Underflow__Environment_multiply_06");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_07()).runTest("CWE191_Integer_Underflow__Environment_multiply_07");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_08()).runTest("CWE191_Integer_Underflow__Environment_multiply_08");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_09()).runTest("CWE191_Integer_Underflow__Environment_multiply_09");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_10()).runTest("CWE191_Integer_Underflow__Environment_multiply_10");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_11()).runTest("CWE191_Integer_Underflow__Environment_multiply_11");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_12()).runTest("CWE191_Integer_Underflow__Environment_multiply_12");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_13()).runTest("CWE191_Integer_Underflow__Environment_multiply_13");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_14()).runTest("CWE191_Integer_Underflow__Environment_multiply_14");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_15()).runTest("CWE191_Integer_Underflow__Environment_multiply_15");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_16()).runTest("CWE191_Integer_Underflow__Environment_multiply_16");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_17()).runTest("CWE191_Integer_Underflow__Environment_multiply_17");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_19()).runTest("CWE191_Integer_Underflow__Environment_multiply_19");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_31()).runTest("CWE191_Integer_Underflow__Environment_multiply_31");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_41()).runTest("CWE191_Integer_Underflow__Environment_multiply_41");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_42()).runTest("CWE191_Integer_Underflow__Environment_multiply_42");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_45()).runTest("CWE191_Integer_Underflow__Environment_multiply_45");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_51a()).runTest("CWE191_Integer_Underflow__Environment_multiply_51a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_52a()).runTest("CWE191_Integer_Underflow__Environment_multiply_52a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_53a()).runTest("CWE191_Integer_Underflow__Environment_multiply_53a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_54a()).runTest("CWE191_Integer_Underflow__Environment_multiply_54a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_61a()).runTest("CWE191_Integer_Underflow__Environment_multiply_61a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_66a()).runTest("CWE191_Integer_Underflow__Environment_multiply_66a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_67a()).runTest("CWE191_Integer_Underflow__Environment_multiply_67a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_multiply_68a()).runTest("CWE191_Integer_Underflow__Environment_multiply_68a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_01()).runTest("CWE191_Integer_Underflow__Environment_subtract_01");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_02()).runTest("CWE191_Integer_Underflow__Environment_subtract_02");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_03()).runTest("CWE191_Integer_Underflow__Environment_subtract_03");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_04()).runTest("CWE191_Integer_Underflow__Environment_subtract_04");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_05()).runTest("CWE191_Integer_Underflow__Environment_subtract_05");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_06()).runTest("CWE191_Integer_Underflow__Environment_subtract_06");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_07()).runTest("CWE191_Integer_Underflow__Environment_subtract_07");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_08()).runTest("CWE191_Integer_Underflow__Environment_subtract_08");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_09()).runTest("CWE191_Integer_Underflow__Environment_subtract_09");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_10()).runTest("CWE191_Integer_Underflow__Environment_subtract_10");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_11()).runTest("CWE191_Integer_Underflow__Environment_subtract_11");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_12()).runTest("CWE191_Integer_Underflow__Environment_subtract_12");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_13()).runTest("CWE191_Integer_Underflow__Environment_subtract_13");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_14()).runTest("CWE191_Integer_Underflow__Environment_subtract_14");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_15()).runTest("CWE191_Integer_Underflow__Environment_subtract_15");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_16()).runTest("CWE191_Integer_Underflow__Environment_subtract_16");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_17()).runTest("CWE191_Integer_Underflow__Environment_subtract_17");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_19()).runTest("CWE191_Integer_Underflow__Environment_subtract_19");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_31()).runTest("CWE191_Integer_Underflow__Environment_subtract_31");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_41()).runTest("CWE191_Integer_Underflow__Environment_subtract_41");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_42()).runTest("CWE191_Integer_Underflow__Environment_subtract_42");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_45()).runTest("CWE191_Integer_Underflow__Environment_subtract_45");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_51a()).runTest("CWE191_Integer_Underflow__Environment_subtract_51a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_52a()).runTest("CWE191_Integer_Underflow__Environment_subtract_52a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_53a()).runTest("CWE191_Integer_Underflow__Environment_subtract_53a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_54a()).runTest("CWE191_Integer_Underflow__Environment_subtract_54a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_61a()).runTest("CWE191_Integer_Underflow__Environment_subtract_61a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_66a()).runTest("CWE191_Integer_Underflow__Environment_subtract_66a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_67a()).runTest("CWE191_Integer_Underflow__Environment_subtract_67a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__Environment_subtract_68a()).runTest("CWE191_Integer_Underflow__Environment_subtract_68a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_01()).runTest("CWE191_Integer_Underflow__fromDB_multiply_01");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_02()).runTest("CWE191_Integer_Underflow__fromDB_multiply_02");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_03()).runTest("CWE191_Integer_Underflow__fromDB_multiply_03");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_04()).runTest("CWE191_Integer_Underflow__fromDB_multiply_04");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_05()).runTest("CWE191_Integer_Underflow__fromDB_multiply_05");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_06()).runTest("CWE191_Integer_Underflow__fromDB_multiply_06");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_07()).runTest("CWE191_Integer_Underflow__fromDB_multiply_07");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_08()).runTest("CWE191_Integer_Underflow__fromDB_multiply_08");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_09()).runTest("CWE191_Integer_Underflow__fromDB_multiply_09");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_10()).runTest("CWE191_Integer_Underflow__fromDB_multiply_10");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_11()).runTest("CWE191_Integer_Underflow__fromDB_multiply_11");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_12()).runTest("CWE191_Integer_Underflow__fromDB_multiply_12");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_13()).runTest("CWE191_Integer_Underflow__fromDB_multiply_13");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_14()).runTest("CWE191_Integer_Underflow__fromDB_multiply_14");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_15()).runTest("CWE191_Integer_Underflow__fromDB_multiply_15");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_16()).runTest("CWE191_Integer_Underflow__fromDB_multiply_16");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_17()).runTest("CWE191_Integer_Underflow__fromDB_multiply_17");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_19()).runTest("CWE191_Integer_Underflow__fromDB_multiply_19");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_31()).runTest("CWE191_Integer_Underflow__fromDB_multiply_31");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_41()).runTest("CWE191_Integer_Underflow__fromDB_multiply_41");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_42()).runTest("CWE191_Integer_Underflow__fromDB_multiply_42");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_45()).runTest("CWE191_Integer_Underflow__fromDB_multiply_45");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_51a()).runTest("CWE191_Integer_Underflow__fromDB_multiply_51a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_52a()).runTest("CWE191_Integer_Underflow__fromDB_multiply_52a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_53a()).runTest("CWE191_Integer_Underflow__fromDB_multiply_53a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_54a()).runTest("CWE191_Integer_Underflow__fromDB_multiply_54a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_61a()).runTest("CWE191_Integer_Underflow__fromDB_multiply_61a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_66a()).runTest("CWE191_Integer_Underflow__fromDB_multiply_66a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_67a()).runTest("CWE191_Integer_Underflow__fromDB_multiply_67a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_multiply_68a()).runTest("CWE191_Integer_Underflow__fromDB_multiply_68a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_01()).runTest("CWE191_Integer_Underflow__fromDB_subtract_01");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_02()).runTest("CWE191_Integer_Underflow__fromDB_subtract_02");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_03()).runTest("CWE191_Integer_Underflow__fromDB_subtract_03");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_04()).runTest("CWE191_Integer_Underflow__fromDB_subtract_04");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_05()).runTest("CWE191_Integer_Underflow__fromDB_subtract_05");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_06()).runTest("CWE191_Integer_Underflow__fromDB_subtract_06");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_07()).runTest("CWE191_Integer_Underflow__fromDB_subtract_07");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_08()).runTest("CWE191_Integer_Underflow__fromDB_subtract_08");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_09()).runTest("CWE191_Integer_Underflow__fromDB_subtract_09");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_10()).runTest("CWE191_Integer_Underflow__fromDB_subtract_10");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_11()).runTest("CWE191_Integer_Underflow__fromDB_subtract_11");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_12()).runTest("CWE191_Integer_Underflow__fromDB_subtract_12");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_13()).runTest("CWE191_Integer_Underflow__fromDB_subtract_13");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_14()).runTest("CWE191_Integer_Underflow__fromDB_subtract_14");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_15()).runTest("CWE191_Integer_Underflow__fromDB_subtract_15");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_16()).runTest("CWE191_Integer_Underflow__fromDB_subtract_16");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_17()).runTest("CWE191_Integer_Underflow__fromDB_subtract_17");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_19()).runTest("CWE191_Integer_Underflow__fromDB_subtract_19");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_31()).runTest("CWE191_Integer_Underflow__fromDB_subtract_31");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_41()).runTest("CWE191_Integer_Underflow__fromDB_subtract_41");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_42()).runTest("CWE191_Integer_Underflow__fromDB_subtract_42");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_45()).runTest("CWE191_Integer_Underflow__fromDB_subtract_45");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_51a()).runTest("CWE191_Integer_Underflow__fromDB_subtract_51a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_52a()).runTest("CWE191_Integer_Underflow__fromDB_subtract_52a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_53a()).runTest("CWE191_Integer_Underflow__fromDB_subtract_53a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_54a()).runTest("CWE191_Integer_Underflow__fromDB_subtract_54a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_61a()).runTest("CWE191_Integer_Underflow__fromDB_subtract_61a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_66a()).runTest("CWE191_Integer_Underflow__fromDB_subtract_66a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_67a()).runTest("CWE191_Integer_Underflow__fromDB_subtract_67a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromDB_subtract_68a()).runTest("CWE191_Integer_Underflow__fromDB_subtract_68a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_01()).runTest("CWE191_Integer_Underflow__fromFile_multiply_01");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_02()).runTest("CWE191_Integer_Underflow__fromFile_multiply_02");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_03()).runTest("CWE191_Integer_Underflow__fromFile_multiply_03");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_04()).runTest("CWE191_Integer_Underflow__fromFile_multiply_04");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_05()).runTest("CWE191_Integer_Underflow__fromFile_multiply_05");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_06()).runTest("CWE191_Integer_Underflow__fromFile_multiply_06");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_07()).runTest("CWE191_Integer_Underflow__fromFile_multiply_07");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_08()).runTest("CWE191_Integer_Underflow__fromFile_multiply_08");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_09()).runTest("CWE191_Integer_Underflow__fromFile_multiply_09");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_10()).runTest("CWE191_Integer_Underflow__fromFile_multiply_10");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_11()).runTest("CWE191_Integer_Underflow__fromFile_multiply_11");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_12()).runTest("CWE191_Integer_Underflow__fromFile_multiply_12");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_13()).runTest("CWE191_Integer_Underflow__fromFile_multiply_13");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_14()).runTest("CWE191_Integer_Underflow__fromFile_multiply_14");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_15()).runTest("CWE191_Integer_Underflow__fromFile_multiply_15");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_16()).runTest("CWE191_Integer_Underflow__fromFile_multiply_16");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_17()).runTest("CWE191_Integer_Underflow__fromFile_multiply_17");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_19()).runTest("CWE191_Integer_Underflow__fromFile_multiply_19");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_31()).runTest("CWE191_Integer_Underflow__fromFile_multiply_31");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_41()).runTest("CWE191_Integer_Underflow__fromFile_multiply_41");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_42()).runTest("CWE191_Integer_Underflow__fromFile_multiply_42");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_45()).runTest("CWE191_Integer_Underflow__fromFile_multiply_45");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_51a()).runTest("CWE191_Integer_Underflow__fromFile_multiply_51a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_52a()).runTest("CWE191_Integer_Underflow__fromFile_multiply_52a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_53a()).runTest("CWE191_Integer_Underflow__fromFile_multiply_53a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_54a()).runTest("CWE191_Integer_Underflow__fromFile_multiply_54a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_61a()).runTest("CWE191_Integer_Underflow__fromFile_multiply_61a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_66a()).runTest("CWE191_Integer_Underflow__fromFile_multiply_66a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_67a()).runTest("CWE191_Integer_Underflow__fromFile_multiply_67a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_multiply_68a()).runTest("CWE191_Integer_Underflow__fromFile_multiply_68a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_01()).runTest("CWE191_Integer_Underflow__fromFile_subtract_01");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_02()).runTest("CWE191_Integer_Underflow__fromFile_subtract_02");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_03()).runTest("CWE191_Integer_Underflow__fromFile_subtract_03");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_04()).runTest("CWE191_Integer_Underflow__fromFile_subtract_04");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_05()).runTest("CWE191_Integer_Underflow__fromFile_subtract_05");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_06()).runTest("CWE191_Integer_Underflow__fromFile_subtract_06");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_07()).runTest("CWE191_Integer_Underflow__fromFile_subtract_07");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_08()).runTest("CWE191_Integer_Underflow__fromFile_subtract_08");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_09()).runTest("CWE191_Integer_Underflow__fromFile_subtract_09");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_10()).runTest("CWE191_Integer_Underflow__fromFile_subtract_10");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_11()).runTest("CWE191_Integer_Underflow__fromFile_subtract_11");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_12()).runTest("CWE191_Integer_Underflow__fromFile_subtract_12");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_13()).runTest("CWE191_Integer_Underflow__fromFile_subtract_13");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_14()).runTest("CWE191_Integer_Underflow__fromFile_subtract_14");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_15()).runTest("CWE191_Integer_Underflow__fromFile_subtract_15");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_16()).runTest("CWE191_Integer_Underflow__fromFile_subtract_16");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_17()).runTest("CWE191_Integer_Underflow__fromFile_subtract_17");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_19()).runTest("CWE191_Integer_Underflow__fromFile_subtract_19");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_31()).runTest("CWE191_Integer_Underflow__fromFile_subtract_31");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_41()).runTest("CWE191_Integer_Underflow__fromFile_subtract_41");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_42()).runTest("CWE191_Integer_Underflow__fromFile_subtract_42");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_45()).runTest("CWE191_Integer_Underflow__fromFile_subtract_45");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_51a()).runTest("CWE191_Integer_Underflow__fromFile_subtract_51a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_52a()).runTest("CWE191_Integer_Underflow__fromFile_subtract_52a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_53a()).runTest("CWE191_Integer_Underflow__fromFile_subtract_53a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_54a()).runTest("CWE191_Integer_Underflow__fromFile_subtract_54a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_61a()).runTest("CWE191_Integer_Underflow__fromFile_subtract_61a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_66a()).runTest("CWE191_Integer_Underflow__fromFile_subtract_66a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_67a()).runTest("CWE191_Integer_Underflow__fromFile_subtract_67a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__fromFile_subtract_68a()).runTest("CWE191_Integer_Underflow__fromFile_subtract_68a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_01()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_01");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_02()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_02");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_03()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_03");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_04()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_04");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_05()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_05");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_06()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_06");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_07()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_07");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_08()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_08");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_09()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_09");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_10()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_10");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_11()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_11");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_12()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_12");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_13()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_13");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_14()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_14");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_15()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_15");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_16()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_16");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_17()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_17");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_19()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_19");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_31()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_31");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_41()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_41");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_42()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_42");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_45()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_45");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_51a()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_51a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_52a()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_52a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_53a()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_53a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_54a()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_54a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_61a()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_61a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_66a()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_66a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_67a()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_67a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_multiply_68a()).runTest("CWE191_Integer_Underflow__listen_tcp_multiply_68a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_01()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_01");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_02()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_02");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_03()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_03");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_04()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_04");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_05()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_05");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_06()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_06");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_07()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_07");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_08()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_08");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_09()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_09");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_10()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_10");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_11()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_11");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_12()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_12");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_13()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_13");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_14()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_14");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_15()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_15");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_16()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_16");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_17()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_17");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_19()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_19");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_31()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_31");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_41()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_41");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_42()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_42");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_45()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_45");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_51a()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_51a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_52a()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_52a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_53a()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_53a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_54a()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_54a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_61a()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_61a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_66a()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_66a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_67a()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_67a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__listen_tcp_subtract_68a()).runTest("CWE191_Integer_Underflow__listen_tcp_subtract_68a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_01()).runTest("CWE191_Integer_Underflow__min_multiply_01");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_02()).runTest("CWE191_Integer_Underflow__min_multiply_02");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_03()).runTest("CWE191_Integer_Underflow__min_multiply_03");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_04()).runTest("CWE191_Integer_Underflow__min_multiply_04");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_05()).runTest("CWE191_Integer_Underflow__min_multiply_05");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_06()).runTest("CWE191_Integer_Underflow__min_multiply_06");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_07()).runTest("CWE191_Integer_Underflow__min_multiply_07");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_08()).runTest("CWE191_Integer_Underflow__min_multiply_08");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_09()).runTest("CWE191_Integer_Underflow__min_multiply_09");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_10()).runTest("CWE191_Integer_Underflow__min_multiply_10");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_11()).runTest("CWE191_Integer_Underflow__min_multiply_11");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_12()).runTest("CWE191_Integer_Underflow__min_multiply_12");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_13()).runTest("CWE191_Integer_Underflow__min_multiply_13");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_14()).runTest("CWE191_Integer_Underflow__min_multiply_14");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_15()).runTest("CWE191_Integer_Underflow__min_multiply_15");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_16()).runTest("CWE191_Integer_Underflow__min_multiply_16");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_17()).runTest("CWE191_Integer_Underflow__min_multiply_17");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_19()).runTest("CWE191_Integer_Underflow__min_multiply_19");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_31()).runTest("CWE191_Integer_Underflow__min_multiply_31");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_41()).runTest("CWE191_Integer_Underflow__min_multiply_41");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_42()).runTest("CWE191_Integer_Underflow__min_multiply_42");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_45()).runTest("CWE191_Integer_Underflow__min_multiply_45");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_51a()).runTest("CWE191_Integer_Underflow__min_multiply_51a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_52a()).runTest("CWE191_Integer_Underflow__min_multiply_52a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_53a()).runTest("CWE191_Integer_Underflow__min_multiply_53a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_54a()).runTest("CWE191_Integer_Underflow__min_multiply_54a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_61a()).runTest("CWE191_Integer_Underflow__min_multiply_61a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_66a()).runTest("CWE191_Integer_Underflow__min_multiply_66a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_67a()).runTest("CWE191_Integer_Underflow__min_multiply_67a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_multiply_68a()).runTest("CWE191_Integer_Underflow__min_multiply_68a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_01()).runTest("CWE191_Integer_Underflow__min_subtract_01");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_02()).runTest("CWE191_Integer_Underflow__min_subtract_02");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_03()).runTest("CWE191_Integer_Underflow__min_subtract_03");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_04()).runTest("CWE191_Integer_Underflow__min_subtract_04");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_05()).runTest("CWE191_Integer_Underflow__min_subtract_05");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_06()).runTest("CWE191_Integer_Underflow__min_subtract_06");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_07()).runTest("CWE191_Integer_Underflow__min_subtract_07");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_08()).runTest("CWE191_Integer_Underflow__min_subtract_08");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_09()).runTest("CWE191_Integer_Underflow__min_subtract_09");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_10()).runTest("CWE191_Integer_Underflow__min_subtract_10");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_11()).runTest("CWE191_Integer_Underflow__min_subtract_11");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_12()).runTest("CWE191_Integer_Underflow__min_subtract_12");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_13()).runTest("CWE191_Integer_Underflow__min_subtract_13");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_14()).runTest("CWE191_Integer_Underflow__min_subtract_14");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_15()).runTest("CWE191_Integer_Underflow__min_subtract_15");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_16()).runTest("CWE191_Integer_Underflow__min_subtract_16");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_17()).runTest("CWE191_Integer_Underflow__min_subtract_17");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_19()).runTest("CWE191_Integer_Underflow__min_subtract_19");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_31()).runTest("CWE191_Integer_Underflow__min_subtract_31");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_41()).runTest("CWE191_Integer_Underflow__min_subtract_41");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_42()).runTest("CWE191_Integer_Underflow__min_subtract_42");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_45()).runTest("CWE191_Integer_Underflow__min_subtract_45");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_51a()).runTest("CWE191_Integer_Underflow__min_subtract_51a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_52a()).runTest("CWE191_Integer_Underflow__min_subtract_52a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_53a()).runTest("CWE191_Integer_Underflow__min_subtract_53a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_54a()).runTest("CWE191_Integer_Underflow__min_subtract_54a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_61a()).runTest("CWE191_Integer_Underflow__min_subtract_61a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_66a()).runTest("CWE191_Integer_Underflow__min_subtract_66a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_67a()).runTest("CWE191_Integer_Underflow__min_subtract_67a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__min_subtract_68a()).runTest("CWE191_Integer_Underflow__min_subtract_68a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_01()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_01");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_02()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_02");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_03()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_03");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_04()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_04");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_05()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_05");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_06()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_06");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_07()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_07");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_08()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_08");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_09()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_09");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_10()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_10");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_11()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_11");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_12()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_12");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_13()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_13");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_14()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_14");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_15()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_15");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_16()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_16");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_17()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_17");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_19()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_19");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_31()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_31");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_41()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_41");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_42()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_42");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_45()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_45");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_51a()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_51a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_52a()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_52a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_53a()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_53a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_54a()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_54a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_61a()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_61a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_66a()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_66a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_67a()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_67a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_multiply_68a()).runTest("CWE191_Integer_Underflow__PropertiesFile_multiply_68a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_01()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_01");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_02()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_02");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_03()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_03");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_04()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_04");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_05()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_05");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_06()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_06");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_07()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_07");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_08()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_08");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_09()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_09");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_10()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_10");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_11()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_11");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_12()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_12");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_13()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_13");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_14()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_14");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_15()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_15");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_16()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_16");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_17()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_17");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_19()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_19");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_31()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_31");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_41()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_41");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_42()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_42");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_45()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_45");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_51a()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_51a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_52a()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_52a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_53a()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_53a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_54a()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_54a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_61a()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_61a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_66a()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_66a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_67a()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_67a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__PropertiesFile_subtract_68a()).runTest("CWE191_Integer_Underflow__PropertiesFile_subtract_68a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_01()).runTest("CWE191_Integer_Underflow__random_multiply_01");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_02()).runTest("CWE191_Integer_Underflow__random_multiply_02");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_03()).runTest("CWE191_Integer_Underflow__random_multiply_03");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_04()).runTest("CWE191_Integer_Underflow__random_multiply_04");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_05()).runTest("CWE191_Integer_Underflow__random_multiply_05");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_06()).runTest("CWE191_Integer_Underflow__random_multiply_06");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_07()).runTest("CWE191_Integer_Underflow__random_multiply_07");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_08()).runTest("CWE191_Integer_Underflow__random_multiply_08");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_09()).runTest("CWE191_Integer_Underflow__random_multiply_09");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_10()).runTest("CWE191_Integer_Underflow__random_multiply_10");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_11()).runTest("CWE191_Integer_Underflow__random_multiply_11");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_12()).runTest("CWE191_Integer_Underflow__random_multiply_12");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_13()).runTest("CWE191_Integer_Underflow__random_multiply_13");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_14()).runTest("CWE191_Integer_Underflow__random_multiply_14");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_15()).runTest("CWE191_Integer_Underflow__random_multiply_15");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_16()).runTest("CWE191_Integer_Underflow__random_multiply_16");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_17()).runTest("CWE191_Integer_Underflow__random_multiply_17");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_19()).runTest("CWE191_Integer_Underflow__random_multiply_19");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_31()).runTest("CWE191_Integer_Underflow__random_multiply_31");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_41()).runTest("CWE191_Integer_Underflow__random_multiply_41");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_42()).runTest("CWE191_Integer_Underflow__random_multiply_42");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_45()).runTest("CWE191_Integer_Underflow__random_multiply_45");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_51a()).runTest("CWE191_Integer_Underflow__random_multiply_51a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_52a()).runTest("CWE191_Integer_Underflow__random_multiply_52a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_53a()).runTest("CWE191_Integer_Underflow__random_multiply_53a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_54a()).runTest("CWE191_Integer_Underflow__random_multiply_54a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_61a()).runTest("CWE191_Integer_Underflow__random_multiply_61a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_66a()).runTest("CWE191_Integer_Underflow__random_multiply_66a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_67a()).runTest("CWE191_Integer_Underflow__random_multiply_67a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_multiply_68a()).runTest("CWE191_Integer_Underflow__random_multiply_68a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_01()).runTest("CWE191_Integer_Underflow__random_subtract_01");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_02()).runTest("CWE191_Integer_Underflow__random_subtract_02");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_03()).runTest("CWE191_Integer_Underflow__random_subtract_03");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_04()).runTest("CWE191_Integer_Underflow__random_subtract_04");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_05()).runTest("CWE191_Integer_Underflow__random_subtract_05");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_06()).runTest("CWE191_Integer_Underflow__random_subtract_06");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_07()).runTest("CWE191_Integer_Underflow__random_subtract_07");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_08()).runTest("CWE191_Integer_Underflow__random_subtract_08");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_09()).runTest("CWE191_Integer_Underflow__random_subtract_09");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_10()).runTest("CWE191_Integer_Underflow__random_subtract_10");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_11()).runTest("CWE191_Integer_Underflow__random_subtract_11");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_12()).runTest("CWE191_Integer_Underflow__random_subtract_12");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_13()).runTest("CWE191_Integer_Underflow__random_subtract_13");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_14()).runTest("CWE191_Integer_Underflow__random_subtract_14");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_15()).runTest("CWE191_Integer_Underflow__random_subtract_15");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_16()).runTest("CWE191_Integer_Underflow__random_subtract_16");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_17()).runTest("CWE191_Integer_Underflow__random_subtract_17");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_19()).runTest("CWE191_Integer_Underflow__random_subtract_19");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_31()).runTest("CWE191_Integer_Underflow__random_subtract_31");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_41()).runTest("CWE191_Integer_Underflow__random_subtract_41");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_42()).runTest("CWE191_Integer_Underflow__random_subtract_42");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_45()).runTest("CWE191_Integer_Underflow__random_subtract_45");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_51a()).runTest("CWE191_Integer_Underflow__random_subtract_51a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_52a()).runTest("CWE191_Integer_Underflow__random_subtract_52a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_53a()).runTest("CWE191_Integer_Underflow__random_subtract_53a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_54a()).runTest("CWE191_Integer_Underflow__random_subtract_54a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_61a()).runTest("CWE191_Integer_Underflow__random_subtract_61a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_66a()).runTest("CWE191_Integer_Underflow__random_subtract_66a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_67a()).runTest("CWE191_Integer_Underflow__random_subtract_67a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__random_subtract_68a()).runTest("CWE191_Integer_Underflow__random_subtract_68a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_01()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_01");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_02()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_02");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_03()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_03");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_04()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_04");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_05()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_05");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_06()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_06");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_07()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_07");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_08()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_08");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_09()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_09");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_10()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_10");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_11()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_11");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_12()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_12");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_13()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_13");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_14()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_14");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_15()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_15");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_16()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_16");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_17()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_17");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_19()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_19");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_31()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_31");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_41()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_41");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_42()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_42");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_45()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_45");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_51a()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_51a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_52a()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_52a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_53a()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_53a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_54a()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_54a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_61a()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_61a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_66a()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_66a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_67a()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_67a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_multiply_68a()).runTest("CWE191_Integer_Underflow__URLConnection_multiply_68a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_01()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_01");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_02()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_02");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_03()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_03");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_04()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_04");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_05()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_05");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_06()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_06");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_07()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_07");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_08()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_08");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_09()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_09");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_10()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_10");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_11()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_11");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_12()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_12");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_13()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_13");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_14()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_14");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_15()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_15");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_16()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_16");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_17()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_17");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_19()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_19");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_31()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_31");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_41()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_41");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_42()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_42");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_45()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_45");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_51a()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_51a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_52a()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_52a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_53a()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_53a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_54a()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_54a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_61a()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_61a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_66a()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_66a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_67a()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_67a");
			(new testcases.CWE191_Integer_Underflow.CWE191_Integer_Underflow__URLConnection_subtract_68a()).runTest("CWE191_Integer_Underflow__URLConnection_subtract_68a");
			/* END-AUTOGENERATED-JAVA-TESTS-1 */
}

private static void runTestCWE2() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

			/* END-AUTOGENERATED-JAVA-TESTS-2 */
}

private static void runTestCWE3() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

			/* END-AUTOGENERATED-JAVA-TESTS-3 */
}

private static void runTestCWE4() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

			/* END-AUTOGENERATED-JAVA-TESTS-4 */
}

private static void runTestCWE5() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

			/* END-AUTOGENERATED-JAVA-TESTS-5 */
}

private static void runTestCWE6() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

			/* END-AUTOGENERATED-JAVA-TESTS-6 */
}

private static void runTestCWE7() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

			/* END-AUTOGENERATED-JAVA-TESTS-7 */
}

private static void runTestCWE8() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

			/* END-AUTOGENERATED-JAVA-TESTS-8 */
}

private static void runTestCWE9() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

			/* END-AUTOGENERATED-JAVA-TESTS-9 */
}
}