package testcasesupport;

import javax.servlet.http.*;

public class ServletMain extends HttpServlet {

	private static final long serialVersionUID = 1L; /* needed since Servlets are serializable */
	
	

	public void doPost(HttpServletRequest request, HttpServletResponse response) {
		doGet(request, response);
	}

	public void doGet(HttpServletRequest request, HttpServletResponse response) {
		doGetCWE1(request, response);
		doGetCWE2(request, response);
		doGetCWE3(request, response);
		doGetCWE4(request, response);
		doGetCWE5(request, response);
		doGetCWE6(request, response);
		doGetCWE7(request, response);
		doGetCWE8(request, response);
		doGetCWE9(request, response);
	}
	
	private static void doGetCWE1(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-1 */

			/* END-AUTOGENERATED-SERVLET-TESTS-1 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE1 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}
		
	private static void doGetCWE2(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-2 */

			/* END-AUTOGENERATED-SERVLET-TESTS-2 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE2 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}
		
	private static void doGetCWE3(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-3 */

			/* END-AUTOGENERATED-SERVLET-TESTS-3 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE3 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}

	private static void doGetCWE4(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-4 */

			/* END-AUTOGENERATED-SERVLET-TESTS-4 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE4 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}
		
	private static void doGetCWE5(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-5 */

			/* END-AUTOGENERATED-SERVLET-TESTS-5 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE5 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {

				System.out.println("  " + ste.toString());
			} 
		}
	}		
		
	private static void doGetCWE6(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-6 */

			/* END-AUTOGENERATED-SERVLET-TESTS-6 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE6 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}

	private static void doGetCWE7(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-7 */

			/* END-AUTOGENERATED-SERVLET-TESTS-7 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE7 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}		
	
	private static void doGetCWE8(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-8 */
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_01()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_02()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_03()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_04()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_05()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_06()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_07()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_08()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_09()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_10()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_11()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_12()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_13()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_14()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_15()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_16()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_17()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_19()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_31()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_41()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_42()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_45()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_51a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_52a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_53a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_54a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_61a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_66a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_67a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_68a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_connect_tcp_71a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_01()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_02()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_03()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_04()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_05()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_06()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_07()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_08()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_09()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_10()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_11()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_12()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_13()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_14()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_15()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_16()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_17()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_19()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_31()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_41()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_42()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_45()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_51a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_52a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_53a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_54a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_61a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_66a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_67a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_68a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_console_readLine_71a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_01()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_02()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_03()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_04()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_05()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_06()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_07()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_08()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_09()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_10()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_11()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_12()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_13()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_14()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_15()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_16()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_17()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_19()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_31()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_41()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_42()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_45()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_51a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_52a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_53a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_54a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_61a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_66a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_67a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_68a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_Environment_71a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_01()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_02()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_03()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_04()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_05()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_06()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_07()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_08()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_09()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_10()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_11()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_12()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_13()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_14()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_15()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_16()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_17()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_19()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_31()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_41()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_42()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_45()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_51a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_52a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_53a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_54a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_61a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_66a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_67a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_68a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromDB_71a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_01()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_02()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_03()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_04()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_05()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_06()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_07()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_08()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_09()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_10()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_11()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_12()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_13()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_14()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_15()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_16()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_17()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_19()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_31()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_41()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_42()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_45()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_51a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_52a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_53a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_54a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_61a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_66a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_67a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_68a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_fromFile_71a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_01()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_02()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_03()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_04()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_05()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_06()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_07()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_08()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_09()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_10()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_11()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_12()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_13()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_14()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_15()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_16()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_17()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_19()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_31()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_41()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_42()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_45()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_51a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_52a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_53a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_54a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_61a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_66a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_67a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_68a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getCookiesServlet_71a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_01()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_02()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_03()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_04()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_05()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_06()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_07()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_08()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_09()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_10()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_11()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_12()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_13()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_14()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_15()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_16()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_17()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_19()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_31()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_41()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_42()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_45()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_51a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_52a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_53a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_54a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_61a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_66a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_67a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_68a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getParameterServlet_71a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_01()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_02()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_03()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_04()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_05()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_06()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_07()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_08()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_09()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_10()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_11()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_12()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_13()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_14()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_15()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_16()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_17()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_19()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_31()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_41()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_42()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_45()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_51a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_52a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_53a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_54a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_61a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_66a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_67a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_68a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_getQueryStringServlet_71a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_01()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_02()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_03()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_04()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_05()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_06()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_07()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_08()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_09()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_10()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_11()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_12()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_13()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_14()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_15()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_16()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_17()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_19()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_31()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_41()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_42()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_45()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_51a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_52a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_53a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_54a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_61a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_66a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_67a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_68a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_listen_tcp_71a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_01()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_02()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_03()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_04()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_05()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_06()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_07()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_08()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_09()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_10()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_11()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_12()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_13()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_14()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_15()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_16()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_17()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_19()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_31()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_41()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_42()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_45()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_51a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_52a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_53a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_54a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_61a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_66a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_67a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_68a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_PropertiesFile_71a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_01()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_02()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_03()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_04()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_05()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_06()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_07()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_08()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_09()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_10()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_11()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_12()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_13()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_14()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_15()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_16()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_17()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_19()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_31()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_41()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_42()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_45()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_51a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_52a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_53a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_54a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_61a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_66a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_67a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_68a()).runTest(request, response);
			(new testcases.CWE80_XSS.CWE80_XSS__Servlet_URLConnection_71a()).runTest(request, response);
			/* END-AUTOGENERATED-SERVLET-TESTS-8 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE8 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}	
	
	private static void doGetCWE9(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-9 */

			/* END-AUTOGENERATED-SERVLET-TESTS-9 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE9 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}		
}
