package testcasesupport;

public class Main {

	public static void main(String[] args) {
		
		if(args.length != 0) {
		
			if(args[0].equals("-h") || args[0].equals("--help")) {
		
				System.err.println("To use this main, you can either run the program with no " +
				"command line arguments to run all test cases or you can specify one or more classes to test");
				System.err.println("For example:");
				System.err.println("java testcasesupport.Main testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
				System.exit(1);
			}
			
			/* User supplied some class names on the command line, just use those with introspection
			 *
			 * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
			 *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
 			 * could read class names from command line or use
			 * http://sadun-util.sourceforge.net/api/org/sadun/util/
			 * ClassPackageExplorer.html
			 */

			for (String className : args) {

				try {
					
					/* String classNameWithPackage = "testcases." + className; */
					
					/* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

					Class<?> myClass = Class.forName(className);

					AbstractTestCase myObject = (AbstractTestCase) myClass
							.newInstance();

					myObject.runTest(className);

				} catch (Exception ex) {

					IO.writeLine("Could not run test for class " + className);
					ex.printStackTrace();

				}
				
				IO.writeLine(""); /* leave a blank line between classes */

			}

		} else {
		
			/* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
			runTestCWE1();
			runTestCWE2();
			runTestCWE3();
			runTestCWE4();
			runTestCWE5();
			runTestCWE6();
			runTestCWE7();
			runTestCWE8();
			runTestCWE9();
		}			
	}

private static void runTestCWE1() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */

			/* END-AUTOGENERATED-JAVA-TESTS-1 */
}

private static void runTestCWE2() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_01()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_01");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_02()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_02");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_03()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_03");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_04()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_04");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_05()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_05");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_06()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_06");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_07()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_07");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_08()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_08");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_09()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_09");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_10()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_10");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_11()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_11");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_12()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_12");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_13()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_13");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_14()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_14");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_15()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_15");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_16()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_16");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_17()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_17");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_19()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_19");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_31()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_31");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_41()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_41");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_42()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_42");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_45()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_45");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_51a()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_51a");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_52a()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_52a");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_53a()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_53a");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_54a()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_54a");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_61a()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_61a");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_66a()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_66a");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_67a()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_67a");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_68a()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_68a");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__fromFile_71a()).runTest("CWE256_Plaintext_Storage_of_Password__fromFile_71a");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_01()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_01");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_02()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_02");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_03()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_03");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_04()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_04");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_05()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_05");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_06()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_06");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_07()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_07");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_08()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_08");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_09()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_09");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_10()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_10");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_11()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_11");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_12()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_12");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_13()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_13");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_14()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_14");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_15()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_15");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_16()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_16");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_17()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_17");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_19()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_19");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_31()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_31");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_41()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_41");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_42()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_42");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_45()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_45");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_51a()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_51a");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_52a()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_52a");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_53a()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_53a");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_54a()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_54a");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_61a()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_61a");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_66a()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_66a");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_67a()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_67a");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_68a()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_68a");
			(new testcases.CWE256_Plaintext_Storage_of_Password.CWE256_Plaintext_Storage_of_Password__PropertiesFile_71a()).runTest("CWE256_Plaintext_Storage_of_Password__PropertiesFile_71a");
			/* END-AUTOGENERATED-JAVA-TESTS-2 */
}

private static void runTestCWE3() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

			/* END-AUTOGENERATED-JAVA-TESTS-3 */
}

private static void runTestCWE4() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

			/* END-AUTOGENERATED-JAVA-TESTS-4 */
}

private static void runTestCWE5() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

			/* END-AUTOGENERATED-JAVA-TESTS-5 */
}

private static void runTestCWE6() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */

			/* END-AUTOGENERATED-JAVA-TESTS-6 */
}

private static void runTestCWE7() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

			/* END-AUTOGENERATED-JAVA-TESTS-7 */
}

private static void runTestCWE8() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

			/* END-AUTOGENERATED-JAVA-TESTS-8 */
}

private static void runTestCWE9() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

			/* END-AUTOGENERATED-JAVA-TESTS-9 */
}
}